### PR TITLE
Fix admin props failing on duration types

### LINKED ISSUE #239: AdminProperties failing on duration values
AdminPropertiesTests failing w/ 

```java
    Caused by: org.apache.pulsar.shade.com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.Duration` not supported by default: add Module "org.apache.pulsar.shade.com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: java.util.HashMap["connectTimeout"])
    	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
    	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300)
    	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer.serialize(UnsupportedTypeSerializer.java:35)
    	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
    	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
    	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
    	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
    	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
    	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
    	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4568)
    	at org.apache.pulsar.shade.com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3821)
    	at org.apache.pulsar.client.impl.conf.ConfigurationDataUtils.loadData(ConfigurationDataUtils.java:66)
```

### PR DESCRIPTION
**Pull request by onobc**
PATL @cbornet @sobychacko 

Fixes #239

### CODE REVIEW

File: spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java [hunk 1]
```diff
@@ -1815,17 +1815,17 @@ public static class Admin {
 		private Set<String> tlsProtocols;
 
 		/**
-		 * Connection time out.
+		 * Duration to wait for a connection to server to be established.
 		 */
-		private Duration connectTimeout = Duration.ofMinutes(1);
+		private Duration connectionTimeout = Duration.ofMinutes(1);
```
Comment (onobc) [inline spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java:1820]: Although it is called `connectTimeout` internally - that is a factor of it being used for the connectTimeout on the jax-rs client and is the same "connection timeout". I think keeping it named the same outwardly makes it less confusing.

File: spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java [hunk 2]
```diff
@@ -2002,10 +2002,10 @@ public Map<String, Object> buildProperties() {
 			map.from(this::getTlsTrustStorePassword).to(properties.in("tlsTrustStorePassword"));
 			map.from(this::getTlsCiphers).to(properties.in("tlsCiphers"));
 			map.from(this::getTlsProtocols).to(properties.in("tlsProtocols"));
-			map.from(this::getConnectTimeout).to(properties.in("connectTimeout"));
-			map.from(this::getReadTimeout).to(properties.in("readTimeout"));
-			map.from(this::getRequestTimeout).to(properties.in("requestTimeout"));
-			map.from(this::getAutoCertRefreshTime).to(properties.in("autoCertRefreshTime"));
+			map.from(this::getConnectionTimeout).asInt(Duration::toMillis).to(properties.in("connectionTimeoutMs"));
```
Comment (onobc) [inline spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java:2005]: The ConfigurationDataUtils does not support Duration at all. Eventhough the PulsarAdminstration.init mucks w/ the props (removes them) I think turning them into `ms` values like the other time props are all handled makes it consistent .

File: spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarPropertiesTests.java [hunk 3]
```diff
@@ -231,10 +236,15 @@ void adminProperties() {
 			bind(props);
 			Map<String, Object> adminProps = properties.buildAdminProperties();
 
-			// Verify that the props can be loaded in a ClientBuilder
-			assertThatNoException().isThrownBy(() -> PulsarAdmin.builder().loadConf(adminProps));
+			// Verify that the props can NOT be loaded directly via a ClientBuilder due to
+			// the
+			// unknown readTimeout and autoCertRefreshTime properties
+			assertThatRuntimeException().isThrownBy(() -> PulsarAdmin.builder().loadConf(adminProps)).havingCause()
```
Comment (onobc) [inline spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarPropertiesTests.java:242]: Once the duration are out of the picture, the CCD barfs on the unknown props `readTimeout` and `autoCertRefreshTime`. I chose to keep this negative test in here really for consistecy w/ the other tests and also info share to this fact that it can not be directly loaded w/o some intervention.

File: spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarAdministration.java [hunk 4]
```diff
@@ -89,17 +88,20 @@ public void setApplicationContext(ApplicationContext applicationContext) throws
 
 	private void loadConf(PulsarAdminBuilder builder, Map<String, Object> adminConfig) {
 		Map<String, Object> conf = new HashMap<>(adminConfig);
-		if (conf.remove("connectTimeout") instanceof Duration connectTimeout) {
-			builder.connectionTimeout((int) connectTimeout.toMillis(), TimeUnit.MILLISECONDS);
+
+		// Workaround the fact that the PulsarAdminImpl does not attempt to construct the
```
Comment (onobc) [inline spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarAdministration.java:92]: I would like to move this to PulsarAdminBuilderImpl.loadConf like we did for the auth stuff below.

**Comment by onobc** [comment]
I am going to merge this in order to get a 🟢 on the CI as I have a follow on PR to bump to SB3.0.0. 

Any PR suggestions I will gladly handle post-merge (cc: @cbornet )

File: spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java [hunk 5]
```diff
@@ -2002,10 +2002,10 @@ public Map<String, Object> buildProperties() {
...
+			map.from(this::getReadTimeout).asInt(Duration::toMillis).to(properties.in("readTimeoutMs"));
+			map.from(this::getRequestTimeout).asInt(Duration::toMillis).to(properties.in("requestTimeoutMs"));
+			map.from(this::getAutoCertRefreshTime).asInt(Duration::toMillis).to(properties.in("autoCertRefreshTimeMs"));
```
Comment (cbornet) [inline spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java:2008]: For `autoCertRefreshTime` we should convert to seconds.

File: spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java (hunk 2 above)
Comment (cbornet) [reply spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java:2005]: Yes !
And in 2.12, these properties will be handled by CCD: https://github.com/apache/pulsar/pull/17375
The names will be `connectionTimeoutMs`, `requestTimeoutMs`, `readTimeoutMs` and `autoCertRefreshSeconds`

Comment (onobc) [reply spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java:2005]: Awesome! Today I was going to look if there was an issue for that already and if not, contribute. Good to hear this.

File: spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarAdministration.java (hunk 4 above)
Comment (onobc) [reply spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarAdministration.java:92]: Added https://github.com/spring-projects-experimental/spring-pulsar/issues/245 to track replacement once fixed in Pulsar 2.12.
