### PR TITLE
PulsarAdministration now respects auth properties

### LINKED ISSUE #194: Unable to configure authentication on admin client
### Problem
An app using `spring-pulsar` that defines `PulsarTopic` beans will fail to start when the admin required authentication. 

### Cause
The `PulsarAdmin` (admin client) does not convert the `authPluginClassName` and `authParams` into an authentication object like the `PulsarClient` does.

### PR DESCRIPTION
**Pull request by onobc**
This code proposal provides a workaround for the fact that the PulsarAdminBuilder does not respect the auth properties specified in the config map during a `loadConf`. 

### Details
* Commit 1: add test to show the breakage
* Commit 2: fix the breakage
* Commit 3: fix unrelated issue in properties assertion

### Next steps
* Submit fix to Apache Pulsar

Fixes #194

### CODE REVIEW

File: spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java [hunk 1]
```diff
@@ -1609,9 +1610,9 @@ public void setTlsProtocols(Set<String> tlsProtocols) {
 		}
 
 		public Map<String, Object> buildProperties() {
-			if (!StringUtils.hasText(this.getAuthParams()) && !CollectionUtils.isEmpty(this.getAuthentication())) {
+			if (StringUtils.hasText(this.getAuthParams()) && !CollectionUtils.isEmpty(this.getAuthentication())) {
```
Comment (onobc) [inline spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java:1613]: This was another bug that was unrelated to the auth props not being respected, but ultimately this prevented any auth props from being set at all.

File: spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarPropertiesTests.java [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+import org.springframework.boot.context.properties.bind.Binder;
+import org.springframework.boot.context.properties.source.ConfigurationPropertySource;
+import org.springframework.boot.context.properties.source.MapConfigurationPropertySource;
+
+/**
+ * Unit tests for {@link PulsarProperties}.
+ *
+ * @author Chris Bono
+ */
+public class PulsarPropertiesTests {
```
Comment (onobc) [inline spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarPropertiesTests.java:39]: **NOTE:** This is the beginning of the config props tests (#176)

**Review by sobychacko — APPROVED** [review]

**Comment by sobychacko** [comment]
Looks good. Merged upstream.
